### ISSUE TITLE
Manager isn't available on custom image model

### ISSUE THREAD

**Issue by GabrielDumbrava** [divio/django-filer#1025]
Hi!
I'm trying to use a custom defined image model, but it breaks even on empty databases if I have other apps using the FilerFileField, like cmsplugin_filer_file.
If I remove the FilerFileField and replace it with a ForeignKey to my custom model, it passes, but stops in the next app that uses it.

I'm using
`Django==1.10.8
django-filer==1.3.0
cmsplugin-filer==1.1.3
django-polymorphic==1.3
`

Here is a stack trace:

`$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/some/path/to/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/some/path/to/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/some/path/to/env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/some/path/to/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/some/path/to/env/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/some/path/to/env/lib/python2.7/site-packages/cmsplugin_filer_file/models.py", line 9, in <module>
    from filer.fields.file import FilerFileField
  File "/some/path/to/env/lib/python2.7/site-packages/filer/fields/file.py", line 17, in <module>
    from ..models import File
  File "/some/path/to/env/lib/python2.7/site-packages/filer/models/__init__.py", line 6, in <module>
    from .imagemodels import *  # flake8: noqa
  File "/some/path/to/env/lib/python2.7/site-packages/filer/models/imagemodels.py", line 20, in <module>
    class Image(BaseImage):
  File "/some/path/to/env/lib/python2.7/site-packages/polymorphic/base.py", line 99, in __new__
    self.validate_model_manager(new_class.objects, model_name, 'objects')
  File "/some/path/to/env/lib/python2.7/site-packages/django/db/models/manager.py", line 198, in __get__
    cls._meta.swapped,
AttributeError: Manager isn't available; 'filer.Image' has been swapped for 'customizations.models.CustomImage'`

**Comment by yakky** [comment]
This should be addressed in #1030 
As soon as we have 1.3.1 out, I will rebase the Django 2.0 branch that fixes the custom model issues

**Comment by skirsdeda** [comment]
@GabrielDumbrava See #1062 for a detailed explanation why this happens. Your best bet is to use Django 1.11 with django_polymorphic 2.0. If you must use Django 1.10, then you'll have to patch django_polymorphic 1.3.

**Comment by GabrielDumbrava** [comment]
@skirsdeda Thanks for your note! I'll try and upgrade to 1.11. Unfortunately some of the packages kept me at 1.10 at that time.

**Comment by yakky** [comment]
Actually I should have a workaround for this 
See https://github.com/nephila/django-filer/commit/504485aeb3c20335e29c28aba7f3674a5ec18e45#diff-48741132b978ff9b2a0446f822bbe2f1R17

**Comment by yakky** [comment]
I'll try to rebase that branch thus we can see if it fixes the issue

**Comment by skirsdeda** [comment]
@yakky the fix in clipboardadmin is definitely necessary (I must have overlooked that somehow). And when you no longer have direct Image imports, my guess is the error does not appear.

**Comment by yakky** [comment]
This has been fixed with #1063 and polymorphic release
