### ISSUE TITLE
Error with django-suit compatibility

### ISSUE THREAD

**Issue by gdreich** [divio/django-filer#1106]
Hi,
An exception is being thrown when trying to create a new folder. Missing admin site context from make_folder view. https://github.com/divio/django-filer/blob/develop/filer/admin/views.py#L28

django-suit-2.0a1
django-filer-1.4.0
django-1.11

`Internal Server Error: /en/admin/filer/folder/make_folder/
Traceback (most recent call last):
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/gavin/Envs/odims/src/django-filer/filer/admin/views.py", line 63, in make_folder
    return render(request, 'admin/filer/dismiss_popup.html')
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 529, in render
    return self.nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/gavin/Envs/odims/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 172, in render
    values = list(values)
  File "/home/gavin/Envs/odims/src/django-suit/suit/menu.py", line 59, in __iter__
    for each in self.get_menu_items():
  File "/home/gavin/Envs/odims/src/django-suit/suit/menu.py", line 64, in get_menu_items
    self.menu_items = self.build_menu()
  File "/home/gavin/Envs/odims/src/django-suit/suit/menu.py", line 78, in build_menu
    self.map_native_apps()
  File "/home/gavin/Envs/odims/src/django-suit/suit/menu.py", line 116, in map_native_apps
    for native_app in self.available_apps:
TypeError: 'NoneType' object is not iterable
`

**Comment by vThaian** [comment]
Hey @gdreich thanks for your PR. I can't reproduce it locally. Could you give your `suit` configuration form settings.py?
