### ISSUE TITLE
Migrating Problem

### ISSUE THREAD

**Issue by kainbacher** [divio/django-filer#569]
Hi, if i add cmsplugin-filer and then call './managepy migrate' i got this error:

```
Synchronizing apps without migrations:
  Creating tables...
    Creating table cmsplugin_filer_image_filerimage
    Creating table cmsplugin_filer_image_thumbnailoption
    Running deferred SQL...
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/Roland/PythonEnvs/django17-konzett/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column "file_ptr_id" referenced in foreign key constraint does not exist
```

i use:
Django==1.8.3
django-cms==3.1.2
django-filer==0.9.12
cmsplugin-filer==0.10.2

any ideas?

**Comment by yakky** [comment]
@kainbacher How is MIGRATION_MODULES setting set?

**Comment by stefanfoulis** [comment]
closing. please re-open if the issue still exists.
