### ISSUE TITLE
django 1.8 TypeError 

### ISSUE THREAD

**Issue by creimers** [divio/django-filer#587]
With ``django==1.8`` installed, the following error is thrown:
```
Internal Server Error: /de/admin/filer/folder/
Traceback (most recent call last):
  File "/srv/<path-to-project>/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/<path-to-project>/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/<path-to-project>/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/<path-to-project>/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/srv/<path-to-project>/env/local/lib/python2.7/site-packages/filer/admin/folderadmin.py", line 387, in directory_listing
    context = admin_each_context(self.admin_site, request)
  File "/srv/<path-to-project>/env/local/lib/python2.7/site-packages/filer/admin/tools.py", line 12, in admin_each_context
    return admin_site.each_context()
TypeError: each_context() takes exactly 2 arguments (1 given)
```

Apparently, the following line is erroneously evaluated as ``True``:

https://github.com/stefanfoulis/django-filer/blob/master/filer/admin/tools.py#L10

Installing ``1.8.4`` (latest at time of writing) solves the issue.

**Comment by yakky** [comment]
@creimers cannot reproduce with any version of Django 1.8 (from 1.8 and up) in latest filer

**Comment by lory87** [comment]
Gentle ping @creimers. Do you still have this problem with current filer version? Thanks for your feedback.

**Comment by creimers** [comment]
@lory87 I checked and the problem no longer exists.
