### ISSUE TITLE
Error uploading a file in 1.0.2

### ISSUE THREAD

**Issue by ipmb** [divio/django-filer#607]
```
Internal Server Error: /admin/filer/clipboard/operations/upload/
Traceback (most recent call last):
  File "/srv/site/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/site/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/site/lib/python2.7/site-packages/filer/admin/clipboardadmin.py", line 88, in ajax_upload
    'thumbnail': file_obj.icons['32'],
KeyError: '32'
```

**Comment by lory87** [comment]
gentle ping @ipmb. Do you still have this error with current filer version? 1.2.0 . Thank you for your feedback.

**Comment by ipmb** [comment]
I'm no longer working on the project, but I'm guessing this was resolved by https://github.com/divio/django-filer/issues/605
