### ISSUE TITLE
Running management commands fails when using ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by ferrix** [divio/django-filer#630]
I am running Django 1.8.7.

Some fields calls the `static` template tag in their `class Media`. This code gets executed when `INSTALLED_APPS` is processed. Since `collectstatic` is not run yet, resolving the path fails. If `collectstatic` has been run before, this does not happen.

The calls to `static` seem to be redundant. According to Django documentation media file paths are transformed into URLs automatically.

This also affects whitenoise users.

**Comment by Chronial** [comment]
Just also ran into this problem. This commit broke it: https://github.com/divio/django-filer/commit/b29e7cc8d488f5c6c469d29e4027b369b64f60db

Here's the exception:
```
vagrant@v-ston ~/ston> ./manage.py collectstatic
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    django.setup()
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/cmsplugin_filer_image/models.py", line 7, in <module>
    from filer.fields.image import FilerImageField
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/filer/fields/image.py", line 3, in <module>
    from filer.fields.file import (
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/filer/fields/file.py", line 23, in <module>
    class AdminFileWidget(ForeignKeyRawIdWidget):
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/filer/fields/file.py", line 83, in AdminFileWidget
    class Media:
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/filer/fields/file.py", line 85, in Media
    static('filer/js/popup_handling.js'),
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/home/vagrant/virtualenvs/ston/lib/python3.4/site-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'filer/js/popup_handling.js' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7fcde9333048>.
```

**Comment by wilburb** [comment]
I ran into this issue with whitenoise on heroku. I don't know if it is a good workaround, but I committed my local staticfiles/filer directory to my repository and sent them up to heroku with everything else.

**Comment by ferrix** [comment]
My workaround is to first run a separate `collectstatic` without manifests and then again with manifests. This requires either two `settings.py` files or some more black belt magic.

**Comment by Lacrymology** [comment]
:+1:

**Comment by clifff** [comment]
Ran into this too while using Django Pipeline's `pipeline.storage.PipelineStorage` for STATICFILES_STORAGE. Per @ferrix's suggestion, I solved by creating a new environment w/ `STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'`, and running collectstatic with that environment, followed by a run with the real environment.

**Comment by stefanfoulis** [comment]
If static/media files are detected automatically in there, we can just remove them. But we need to be sure that it also work for special storage backends (e.g S3) where the static file might be on a other domain entirely. @ferrix do you happen to know if that would work.
Also we need to make sure there are no regressions for older versions of Django.

**Comment by ferrix** [comment]
@stefanfoulis That is my use case exactly. Standard implementations of StaticFilesStorage are implicitly executed by `static` and the behavior has been described to do the implicit url transformation from Django 1.5 at least (ref: https://docs.djangoproject.com/en/1.5/topics/forms/media/#media-as-a-static-definition) and the offending commit b29e7cc is from 2015. So, this is a trivial change.

**Comment by Chronial** [comment]
@stefanfoulis Please see here for the relevant django source code All the way from 1.5
https://github.com/django/django/blob/1.5/django/forms/widgets.py#L71
to 1.9
https://github.com/django/django/blob/1.9/django/forms/widgets.py#L80

**Comment by stefanfoulis** [comment]
@Chronial @ferrix this should fix the issue, right? #753

**Comment by Chronial** [comment]
@stefanfoulis yes, that's all that's needed.

**Comment by stefanfoulis** [comment]
@Chronial thanks for the quick response

**Comment by mikek** [comment]
#438 is a separate issue. I'll close this one.
