### ISSUE TITLE
Migration error after deleting sqlite3 db

### ISSUE THREAD

**Issue by sedrubal** [divio/django-filer#646]
After deleting the `sqlite3` database I cannot migrate anymore to start from scratch again. (*Is there another way to do this?*)

I'm not 100% sure if this belongs to this repository...

`manage-py migrate` results in:

```python
Operations to perform:
  Synchronize unmigrated apps: treebeard, djangocms_admin_style, sekizai, parler, messages, meta_mixin, cmsplugin_filer_image, taggit_autosuggest, meta, sass_processor, sitemaps, fablab_website, staticfiles
  Apply all migrations: djangocms_text_ckeditor, sessions, admin, cms, djangocms_column, djangocms_teaser, djangocms_video, auth, djangocms_googlemap, djangocms_picture, menus, easy_thumbnails, djangocms_link, contenttypes, djangocms_inherit, djangocms_blog, reversion, djangocms_file, taggit, djangocms_style, sites, filer
Synchronizing apps without migrations:
  Creating tables...
    Creating table cmsplugin_filer_image_filerimage
    Creating table cmsplugin_filer_image_thumbnailoption
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...Traceback (most recent call last):
  File "././djangocms//manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/venv/lib/python3.4/site-packages/django/db/migrations/executor.py", line 100, in migrate
    state.apps  # Render all real_apps -- performance critical
  File "/venv/lib/python3.4/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/venv/lib/python3.4/site-packages/django/db/migrations/state.py", line 166, in apps
    return StateApps(self.real_apps, self.models)
  File "/venv/lib/python3.4/site-packages/django/db/migrations/state.py", line 232, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/venv/lib/python3.4/site-packages/django/db/migrations/state.py", line 270, in render_multiple
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'cmsplugin_filer_image.FilerImage'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies for more
```

### OS:

`Fedora:23`

### Details about local setup:

It's [this project](https://github.com/fau-fablab/website/tree/djangocms_blog). If you want you can inspect all files and even run the docker container...

- django `1.8.7`
- djangocms `3.2.0`
- djangocms blog `0.3.6`
- packages from pypi
- python 3
- virtual environment

### Steps to reproduce:

 - set up a djangocms-blog project with sqlite3 (as you can see in my repository...)
 - `manage.py makemigrations`
 - `manage.py migrate`
 - add some blog posts or do what ever you do with a djangocms...
 - delete the sqlite3 database
 - `manage.py migrate`

Merry christmas ;) :christmas_tree: :santa:

**Comment by joshuajonah** [comment]
This is an issue with the filer cmsplugin, not filer standard.

**Comment by sedrubal** [comment]
Ok, thanks. Should I report it there?

**Comment by joshuajonah** [comment]
Yeah, post it over here: https://github.com/divio/cmsplugin-filer

**Comment by sedrubal** [comment]
Ok, it's now here: https://github.com/divio/cmsplugin-filer/issues/207
