### ISSUE TITLE
django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')

### ISSUE THREAD

**Issue by jfscyberpub** [divio/django-filer#939]
I have upgraded djangocms-picture from 0.2.0 to 2.0.3
This new version requires django-filer.

When I run the migrations, the initial migration generates an error:

```
(0.667) ALTER TABLE `filer_folder` ADD CONSTRAINT `filer_folder_owner_id_be530fb4_fk_auth_user_id` FOREIGN KEY (`owner_id`) REFERENCES `auth_user` (`id`); args=[]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 90, in __exit__
    self.execute(sql)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/jonathan/projects/venvs/cy3/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')
```

Packages I use:

- Django==1.9.11
- django-cms==3.4.1
- django-filer==1.2.5
- django-mptt==0.8.6
- djangocms-picture==2.0.3
- easy-thumbnails==2.3

Any ideas ? Thank you.

**Comment by jfscyberpub** [comment]
For those who meet the same issue, it's because I am using MyISAM engine. I had to convert it to InnoDB. Then it worked.

`ALTER TABLE <table> ENGINE=InnoDB;`
