### ISSUE TITLE
DataError: integer out of range from postgres

### ISSUE THREAD

**Issue by codejoy** [divio/django-filer#984]
I am trying hard to figure out why files somewhere over 2GB do not go into filer.  I think it was working when I was on a sqllite database (and I had the right configurations done for the server to accept it) but I swear since going to a postgres/postgis database, files over 2GB fail for me.  I get this error, is there a field I have to update to handle larger values in the database of the filer table I am guessing?

] Internal Server Error: /admin/filer/clipboard/operations/upload/23/
[Thu Jun 08 15:36:35.028492 2017] [:error] [pid 16900] Traceback (most recent call last):
[Thu Jun 08 15:36:35.028498 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Thu Jun 08 15:36:35.028502 2017] [:error] [pid 16900]     response = self.process_exception_by_middleware(e, request)
[Thu Jun 08 15:36:35.028506 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Thu Jun 08 15:36:35.028510 2017] [:error] [pid 16900]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Jun 08 15:36:35.028514 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Thu Jun 08 15:36:35.028517 2017] [:error] [pid 16900]     return view_func(*args, **kwargs)
[Thu Jun 08 15:36:35.028521 2017] [:error] [pid 16900]   File "/usr/lib/python2.7/site-packages/filer/admin/clipboardadmin.py", line 126, in ajax_upload
[Thu Jun 08 15:36:35.028525 2017] [:error] [pid 16900]     file_obj.save()
[Thu Jun 08 15:36:35.028529 2017] [:error] [pid 16900]   File "/usr/lib/python2.7/site-packages/filer/models/filemodels.py", line 171, in save
[Thu Jun 08 15:36:35.028533 2017] [:error] [pid 16900]     super(File, self).save(*args, **kwargs)
[Thu Jun 08 15:36:35.028536 2017] [:error] [pid 16900]   File "/usr/lib/python2.7/site-packages/polymorphic/models.py", line 90, in save
[Thu Jun 08 15:36:35.028539 2017] [:error] [pid 16900]     return super(PolymorphicModel, self).save(*args, **kwargs)
[Thu Jun 08 15:36:35.028543 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 708, in save
[Thu Jun 08 15:36:35.028546 2017] [:error] [pid 16900]     force_update=force_update, update_fields=update_fields)
[Thu Jun 08 15:36:35.028550 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 736, in save_base
[Thu Jun 08 15:36:35.028553 2017] [:error] [pid 16900]     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
[Thu Jun 08 15:36:35.028557 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 820, in _save_table
[Thu Jun 08 15:36:35.028560 2017] [:error] [pid 16900]     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
[Thu Jun 08 15:36:35.028578 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 859, in _do_insert
[Thu Jun 08 15:36:35.028583 2017] [:error] [pid 16900]     using=using, raw=raw)
[Thu Jun 08 15:36:35.028586 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
[Thu Jun 08 15:36:35.028590 2017] [:error] [pid 16900]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Thu Jun 08 15:36:35.028593 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
[Thu Jun 08 15:36:35.028597 2017] [:error] [pid 16900]     return query.get_compiler(using=using).execute_sql(return_id)
[Thu Jun 08 15:36:35.028600 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
[Thu Jun 08 15:36:35.028603 2017] [:error] [pid 16900]     cursor.execute(sql, params)
[Thu Jun 08 15:36:35.028607 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
[Thu Jun 08 15:36:35.028610 2017] [:error] [pid 16900]     return super(CursorDebugWrapper, self).execute(sql, params)
[Thu Jun 08 15:36:35.028614 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
[Thu Jun 08 15:36:35.028617 2017] [:error] [pid 16900]     return self.cursor.execute(sql, params)
[Thu Jun 08 15:36:35.028620 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
[Thu Jun 08 15:36:35.028624 2017] [:error] [pid 16900]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[Thu Jun 08 15:36:35.028627 2017] [:error] [pid 16900]   File "/usr/lib64/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
[Thu Jun 08 15:36:35.028630 2017] [:error] [pid 16900]     return self.cursor.execute(sql, params)
[Thu Jun 08 15:36:35.028633 2017] [:error] [pid 16900] DataError: integer out of range
[Thu Jun 08 15:36:35.028637 2017] [:error] [pid 16900]

**Comment by yakky** [comment]
thanks for reporting. This has been fixed in #1050 which is due to be released in 1.3.1
